baseURL: "https://jumaffre.github.io"
languageCode: "en"
title: " "
theme: "PaperMod"

params:
  env: production
  hideFooter: true
  defaultTheme: light
  disableThemeToggle: true

  profileMode:
    enabled: true
    title: "## Julien Maffre"
    subtitle: "Research Software Engineer **[@Microsoft](https://www.microsoft.com/en-us/research/people/jumaffre/)**"
    # imageUrl: "<image link>"
    # imageTitle: " "
    # imageWidth: 120
    # imageHeight: 120

  socialIcons:
    - name: github
      url: "https://github.com/jumaffre"
