baseURL: "https://jumaffre.github.io"
languageCode: "en"
title: " "
theme: "PaperMod"

params:
  env: production
  hideFooter: true
  defaultTheme: light
  disableThemeToggle: true

  profileMode:
    enabled: true
    title: "## Julien Maffre"
    subtitle: "Software Engineer **[@Wayve](https://wayve.ai/)**"
    # imageUrl: "<image link>"
    # imageTitle: " "
    # imageWidth: 120
    # imageHeight: 120

  socialIcons:
    - name: github
      url: "https://github.com/jumaffre"
    - name: linkedin
      url: "https://www.linkedin.com/in/julien-maffre-22260a74/"
